language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.1
addons:
  postgresql: "9.4"
before_script:
  - "bin/rake db:create db:test:prepare"
script: "bin/rake spec"
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: always
